= REST to SOAP policy

ifdef::env-github[]
image:https://ci.gravitee.io/buildStatus/icon?job=gravitee-io/gravitee-policy-rest-to-soap/master["Build status", link="https://ci.gravitee.io/job/gravitee-io/job/gravitee-policy-rest-to-soap/"]
image:https://badges.gitter.im/Join Chat.svg["Gitter", link="https://gitter.im/gravitee-io/gravitee-io?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]
endif::[]

== Phase

|===
|onRequest |onResponse

| X
|

|===

== Description

You can use the `rest-to-soap` policy to expose SOAP backend service as a REST API. The policy will pass the SOAP envelope message
to the backend service as a POST request. SOAP envelopes support Expression Language to provide dynamic SOAP actions.

For example, a SOAP API `http(s)://GATEWAY_HOST:GATEWAY_PORT/soap?countryName=France` with the following `rest-to-soap` policy SOAP envelope content:

[source=xml]
----
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope\\\" xmlns:web=\\\"http://www.oorsprong.org/websamples.countryinfo">
   <soap:Header/>
   <soap:Body>
      <web:CountryISOCode>
         <web:sCountryName>{#request.params['countryName']}</web:sCountryName>
      </web:CountryISOCode>
   </soap:Body>
</soap:Envelope>
----

Will give you the ISO country code for `France`.

=== Policy identifier

You can enable or disable the policy with policy identifier `rest-to-soap`.

== Configuration

You can configure the policy with the following options:

|===
|Property |Required |Description |Type |Default

|SOAP Envelope
|X
|
|SOAP envelope used to invoke WS (supports Expression Language)
|

|SOAP Action
|
|
|'SOAPAction' HTTP header sent when invoking WS
|

|Charset
|
|
|This charset will be appended to the `Content-Type` header value
|

|Preserve Query Parameters
|
|
|Whether the query parameters are propagated to the backend SOAP service
|

|===


[source, json]
.Sample
----
"rest-to-soap": {
  "envelope": "<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:web="http://www.oorsprong.org/websamples.countryinfo">
                 <soap:Header/>
                 <soap:Body>
                    <web:ListOfCountryNamesByName/>
                 </soap:Body>
              </soap:Envelope>",
  "soapAction": null
}
----
